INFO:appsvc_profiler.installer:Code Profiler Installer is starting up
INFO:appsvc_profiler.installer:Cleaning up any existing status file which indicated signal handlers initialized status
INFO:appsvc_profiler.installer:Attempting to delete the signal_handler status file for instance id 6ffa4778196b57b05304fc8e83eb2a6bb88ae80d3196f2e02bf8ecfe7c724c68
INFO:appsvc_profiler.installer:successfully deleted the status file
DEBUG:appsvc_profiler.installer:APPSETTING_WEBSITE_ENABLE_DEFAULT_CODE_PROFILER : None
INFO:appsvc_profiler.installer:Attempting to install the default code profiler.
DEBUG:appsvc_profiler.installer:viztracer would save traces to /tmp/6ffa47_profiler_trace.json
INFO:appsvc_profiler.installer:Successfully installed code profiler.
INFO:appsvc_profiler.installer:Signal Handlers SIGUSR for needed code-profiler have been initialized for gunicorn process on instance 6ffa4778196b57b05304fc8e83eb2a6bb88ae80d3196f2e02bf8ecfe7c724c68
DEBUG:appsvc_profiler.installer:Code Profiler Installer is exiting as installation is completed
ERROR:cassandra.datastax.cloud:<urlopen error _ssl.c:1116: The handshake operation timed out>
Traceback (most recent call last):
  File "/opt/python/3.9.19/lib/python3.9/urllib/request.py", line 1346, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/opt/python/3.9.19/lib/python3.9/http/client.py", line 1285, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/opt/python/3.9.19/lib/python3.9/http/client.py", line 1331, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/opt/python/3.9.19/lib/python3.9/http/client.py", line 1280, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/opt/python/3.9.19/lib/python3.9/http/client.py", line 1040, in _send_output
    self.send(msg)
  File "/opt/python/3.9.19/lib/python3.9/http/client.py", line 980, in send
    self.connect()
  File "/opt/python/3.9.19/lib/python3.9/http/client.py", line 1454, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/opt/python/3.9.19/lib/python3.9/ssl.py", line 501, in wrap_socket
    return self.sslsocket_class._create(
  File "/opt/python/3.9.19/lib/python3.9/ssl.py", line 1074, in _create
    self.do_handshake()
  File "/opt/python/3.9.19/lib/python3.9/ssl.py", line 1343, in do_handshake
    self._sslobj.do_handshake()
socket.timeout: _ssl.c:1116: The handshake operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/8dc9524939e911d/antenv/lib/python3.9/site-packages/cassandra/datastax/cloud/__init__.py", line 137, in read_metadata_info
    response = urlopen(url, context=config.ssl_context, timeout=timeout)
  File "/opt/python/3.9.19/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/python/3.9.19/lib/python3.9/urllib/request.py", line 517, in open
    response = self._open(req, data)
  File "/opt/python/3.9.19/lib/python3.9/urllib/request.py", line 534, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/opt/python/3.9.19/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/opt/python/3.9.19/lib/python3.9/urllib/request.py", line 1389, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/opt/python/3.9.19/lib/python3.9/urllib/request.py", line 1349, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error _ssl.c:1116: The handshake operation timed out>
INFO:app:*****************Prediction opening *************************
INFO:app:*****************Prediction opening *************************
