INFO:appsvc_profiler.installer:Code Profiler Installer is starting up
DEBUG:appServiceAppLogs:Waiting for the logs flag to be set
INFO:appsvc_profiler.installer:Cleaning up any existing status file which indicated signal handlers initialized status
DEBUG:appsvc_profiler.installer:APPSETTING_WEBSITE_ENABLE_DEFAULT_CODE_PROFILER : None
INFO:appsvc_profiler.installer:Attempting to install the default code profiler.
DEBUG:appsvc_profiler.installer:viztracer would save traces to /tmp/aa5a7b_profiler_trace.json
INFO:appsvc_profiler.installer:Successfully installed code profiler.
INFO:appsvc_profiler.installer:Signal Handlers SIGUSR for needed code-profiler have been initialized for gunicorn process on instance aa5a7b1e3d657bb5e200ae7d4b6324379854db652dc7780ea09b7547b87142de
DEBUG:appsvc_profiler.installer:Code Profiler Installer is exiting as installation is completed
INFO:app:*****************Prediction opening *************************
INFO:app:*****************Prediction opening *************************
INFO:app:*****************Prediction opening *************************
ERROR:cassandra.datastax.cloud:HTTP Error 401: Unauthorized
Traceback (most recent call last):
  File "/tmp/8dc7167740e9d97/antenv/lib/python3.9/site-packages/cassandra/datastax/cloud/__init__.py", line 137, in read_metadata_info
    response = urlopen(url, context=config.ssl_context, timeout=timeout)
  File "/opt/python/3.9.18/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/python/3.9.18/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/opt/python/3.9.18/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/opt/python/3.9.18/lib/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/opt/python/3.9.18/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/opt/python/3.9.18/lib/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 401: Unauthorized
ERROR:app:Exception on /history [GET]
Traceback (most recent call last):
  File "/tmp/8dc7167740e9d97/antenv/lib/python3.9/site-packages/cassandra/datastax/cloud/__init__.py", line 137, in read_metadata_info
    response = urlopen(url, context=config.ssl_context, timeout=timeout)
  File "/opt/python/3.9.18/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/python/3.9.18/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/opt/python/3.9.18/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/opt/python/3.9.18/lib/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/opt/python/3.9.18/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/opt/python/3.9.18/lib/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 401: Unauthorized

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/8dc7167740e9d97/antenv/lib/python3.9/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/tmp/8dc7167740e9d97/antenv/lib/python3.9/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/tmp/8dc7167740e9d97/antenv/lib/python3.9/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/tmp/8dc7167740e9d97/antenv/lib/python3.9/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/tmp/8dc7167740e9d97/app.py", line 74, in fetchui
    all_entries = fetch_all_entries()
  File "/tmp/8dc7167740e9d97/connect_database.py", line 60, in fetch_all_entries
    cluster, session = connect_to_cassandra()
  File "/tmp/8dc7167740e9d97/connect_database.py", line 24, in connect_to_cassandra
    cluster = Cluster(cloud=cloud_config, auth_provider=auth_provider)
  File "cassandra/cluster.py", line 1172, in cassandra.cluster.Cluster.__init__
  File "/tmp/8dc7167740e9d97/antenv/lib/python3.9/site-packages/cassandra/datastax/cloud/__init__.py", line 91, in get_cloud_config
    config = read_metadata_info(config, cloud_config)
  File "/tmp/8dc7167740e9d97/antenv/lib/python3.9/site-packages/cassandra/datastax/cloud/__init__.py", line 140, in read_metadata_info
    raise DriverException("Unable to connect to the metadata service at %s. "
cassandra.DriverException: Unable to connect to the metadata service at https://74f3ea48-05df-4249-a12b-fac40645190d-us-east-1.db.astra.datastax.com:29080/metadata. Check the cluster status in the cloud console. 
WARNING:cassandra.cluster:Downgrading core protocol version from 66 to 65 for 74f3ea48-05df-4249-a12b-fac40645190d-us-east-1.db.astra.datastax.com:29042:b4f6d9ed-0f1d-3f7a-82f1-a4a7ea4f84d4. To avoid this, it is best practice to explicitly set Cluster(protocol_version) to the version supported by your cluster. http://datastax.github.io/python-driver/api/cassandra/cluster.html#cassandra.cluster.Cluster.protocol_version
WARNING:cassandra.cluster:Downgrading core protocol version from 65 to 5 for 74f3ea48-05df-4249-a12b-fac40645190d-us-east-1.db.astra.datastax.com:29042:b4f6d9ed-0f1d-3f7a-82f1-a4a7ea4f84d4. To avoid this, it is best practice to explicitly set Cluster(protocol_version) to the version supported by your cluster. http://datastax.github.io/python-driver/api/cassandra/cluster.html#cassandra.cluster.Cluster.protocol_version
WARNING:cassandra.cluster:Downgrading core protocol version from 5 to 4 for 74f3ea48-05df-4249-a12b-fac40645190d-us-east-1.db.astra.datastax.com:29042:b4f6d9ed-0f1d-3f7a-82f1-a4a7ea4f84d4. To avoid this, it is best practice to explicitly set Cluster(protocol_version) to the version supported by your cluster. http://datastax.github.io/python-driver/api/cassandra/cluster.html#cassandra.cluster.Cluster.protocol_version
INFO:cassandra.policies:Using datacenter 'us-east-1' for DCAwareRoundRobinPolicy (via host '74f3ea48-05df-4249-a12b-fac40645190d-us-east-1.db.astra.datastax.com:29042:b4f6d9ed-0f1d-3f7a-82f1-a4a7ea4f84d4'); if incorrect, please specify a local_dc to the constructor, or limit contact points to local cluster nodes
WARNING:cassandra.cluster:Found multiple hosts with the same endpoint (74f3ea48-05df-4249-a12b-fac40645190d-us-east-1.db.astra.datastax.com:29042:b4f6d9ed-0f1d-3f7a-82f1-a4a7ea4f84d4). Excluding peer 10.0.0.9
INFO:cassandra.cluster:Cassandra host 74f3ea48-05df-4249-a12b-fac40645190d-us-east-1.db.astra.datastax.com:29042:00694036-11ec-39fb-8238-d79afd9b0e46 removed
INFO:app:*****************Prediction opening *************************
WARNING:cassandra.cluster:Downgrading core protocol version from 66 to 65 for 74f3ea48-05df-4249-a12b-fac40645190d-us-east-1.db.astra.datastax.com:29042:9e3a5bee-3d95-3bf7-90f5-09bd2177324b. To avoid this, it is best practice to explicitly set Cluster(protocol_version) to the version supported by your cluster. http://datastax.github.io/python-driver/api/cassandra/cluster.html#cassandra.cluster.Cluster.protocol_version
WARNING:cassandra.cluster:Downgrading core protocol version from 65 to 5 for 74f3ea48-05df-4249-a12b-fac40645190d-us-east-1.db.astra.datastax.com:29042:9e3a5bee-3d95-3bf7-90f5-09bd2177324b. To avoid this, it is best practice to explicitly set Cluster(protocol_version) to the version supported by your cluster. http://datastax.github.io/python-driver/api/cassandra/cluster.html#cassandra.cluster.Cluster.protocol_version
WARNING:cassandra.cluster:Downgrading core protocol version from 5 to 4 for 74f3ea48-05df-4249-a12b-fac40645190d-us-east-1.db.astra.datastax.com:29042:9e3a5bee-3d95-3bf7-90f5-09bd2177324b. To avoid this, it is best practice to explicitly set Cluster(protocol_version) to the version supported by your cluster. http://datastax.github.io/python-driver/api/cassandra/cluster.html#cassandra.cluster.Cluster.protocol_version
INFO:cassandra.policies:Using datacenter 'us-east-1' for DCAwareRoundRobinPolicy (via host '74f3ea48-05df-4249-a12b-fac40645190d-us-east-1.db.astra.datastax.com:29042:9e3a5bee-3d95-3bf7-90f5-09bd2177324b'); if incorrect, please specify a local_dc to the constructor, or limit contact points to local cluster nodes
WARNING:cassandra.cluster:Found multiple hosts with the same endpoint (74f3ea48-05df-4249-a12b-fac40645190d-us-east-1.db.astra.datastax.com:29042:9e3a5bee-3d95-3bf7-90f5-09bd2177324b). Excluding peer 10.0.0.6
INFO:cassandra.cluster:Cassandra host 74f3ea48-05df-4249-a12b-fac40645190d-us-east-1.db.astra.datastax.com:29042:00694036-11ec-39fb-8238-d79afd9b0e46 removed
INFO:app:*****************Prediction opening *************************
INFO:app:*****************Prediction opening *************************
