INFO:appsvc_profiler.installer:Code Profiler Installer is starting up
DEBUG:appServiceAppLogs:Waiting for the logs flag to be set
INFO:appsvc_profiler.installer:Cleaning up any existing status file which indicated signal handlers initialized status
INFO:appsvc_profiler.installer:Attempting to delete the signal_handler status file for instance id cc8f72f932c68de6d9cb9fbf1ce31bb68571e50921f809af7a07d0bceb35a578
INFO:appsvc_profiler.installer:successfully deleted the status file
DEBUG:appsvc_profiler.installer:APPSETTING_WEBSITE_ENABLE_DEFAULT_CODE_PROFILER : None
INFO:appsvc_profiler.installer:Attempting to install the default code profiler.
DEBUG:appsvc_profiler.installer:viztracer would save traces to /tmp/cc8f72_profiler_trace.json
INFO:appsvc_profiler.installer:Successfully installed code profiler.
INFO:appsvc_profiler.installer:Signal Handlers SIGUSR for needed code-profiler have been initialized for gunicorn process on instance cc8f72f932c68de6d9cb9fbf1ce31bb68571e50921f809af7a07d0bceb35a578
DEBUG:appsvc_profiler.installer:Code Profiler Installer is exiting as installation is completed
INFO:app:*****************Prediction opening *************************
INFO:app:*****************Prediction opening *************************
INFO:app:*****************Prediction opening *************************
INFO:app:*****************Prediction opening *************************
INFO:app:*****************Prediction for URL started *************************
INFO:app:time_response 0.186852
INFO:app:domain_spf 0
INFO:app:asn_ip 1
INFO:app:time_domain_activation 505
INFO:app:time_domain_expiration 225
INFO:app:qty_ip_resolved 1
INFO:app:qty_nameservers 2
INFO:app:qty_mx_servers None
INFO:app:ttl_hostname 3
INFO:app:tls_ssl_certificate 1
INFO:app:qty_redirects 0
INFO:app:url_google_index 1
INFO:app:domain_google_index 0
INFO:app:url_shortened 0
INFO:app:Domain: www.2345daohang.com
INFO:app:URL: http://www.2345daohang.com
ERROR:cassandra.datastax.cloud:HTTP Error 401: Unauthorized
Traceback (most recent call last):
  File "/tmp/8dc7167740e9d97/antenv/lib/python3.9/site-packages/cassandra/datastax/cloud/__init__.py", line 137, in read_metadata_info
    response = urlopen(url, context=config.ssl_context, timeout=timeout)
  File "/opt/python/3.9.18/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/python/3.9.18/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/opt/python/3.9.18/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/opt/python/3.9.18/lib/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/opt/python/3.9.18/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/opt/python/3.9.18/lib/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 401: Unauthorized
